export { LandingPage } from "./LandingPage";
export { Presentation } from "./Presentation";
export { Header } from "./Header";
export { Footer } from "./Footer";
export { Products } from "./Products";
export { About } from "./About";
export { Navigation } from "./Navigation";
export { Categories } from "./Categories";
export { CardCategory } from "./CardCategory";
